version: '3'
 
services:

  # redis-overcommit-on-host
  redis-overcommit:
    build: redis-overcommit
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm
      - /proc/sys/net:/mnt/net
      - /sys/kernel:/mnt/kernel

  reverseproxy:
    build: nginx
    image: nginx-server
    container_name: nginx-server-container
    ports:
      # port to access: internal port
      - 8984:9999
    restart: always
    networks:
      - backend

  express:
    depends_on:
      - reverseproxy
      - redis
    build:
      context: express
      args:
       - dir=/opt/example.com/
       - port=3000
       - env=dev
    image: express-server
    container_name: express-server-container
    volumes:
      - ./express/src:/opt/example.com/src
      - ./express/dist:/opt/example.com/dist
    networks:
      - backend
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - PORT=3000

  redis:
    image: redis
    build: redis
    container_name: cache
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6379
    depends_on:
      - redis-overcommit
    sysctls:
      - net.core.somaxconn=1024

networks:
  backend:
    driver: "bridge"
volumes:
  express:
    driver: 'local'
